apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mock-database
  labels:
    app: mock-database
    component: database
spec:
  replicas: 50
  selector:
    matchLabels:
      app: mock-database
  template:
    metadata:
      labels:
        app: mock-database
        component: database
        tier: storage
        version: v1.0.0
        workload-type: database
    spec:
      containers:
        - name: worker
          image: busybox:1.36-musl
          command:
            [
              "sh",
              "-c",
              "while true; do echo 'Processing batch job...'; sleep 30; done",
            ]
          resources:
            requests:
              memory: "16Mi"
              cpu: "10m"
            limits:
              memory: "32Mi"
              cpu: "50m"
