apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  labels:
    app.kubernetes.io/name: webhook-server
spec:
  ports:
  - name: webhook-api
    port: 443
    targetPort: 443
  selector:
    app.kubernetes.io/name: webhook-server
---
apiVersion: v1
kind: Pod
metadata:
  name: webhook-server
  labels:
    app.kubernetes.io/name: webhook-server
spec:
  containers:
  - name: webhook-server
    image: webhook:v1
    command: ["./webhook"]
    args:
      - --tls-cert-file=/etc/certs/tls.crt
      - --tls-private-key-file=/etc/certs/tls.key
      - --port=443
    ports:
      - containerPort: 443
    volumeMounts:
    - name: webhook-certs
      mountPath: /etc/certs
      readOnly: true
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
  volumes:
  - name: webhook-certs
    secret:
      secretName: webhook-certs
